version: "2"
services:
    server:
        build: ./server
        expose:
          - ${APP_SERVER_PORT}
        environment:
          API_HOST: ${API_HOST}
          APP_SERVER_PORT: ${APP_SERVER_PORT}
        ports:
            - "${APP_SERVER_PORT}:${APP_SERVER_PORT}"
        volumes:
            - ./server/src:/srv/app/server/src
    client:
        build: ./client
        environment:
          ${REACT_APP_PORT}: ${REACT_APP_PORT}
        ports:
          - "${REACT_APP_PORT}:${REACT_APP_PORT}"
        links:
          - server
    